# Generated by Django 3.2 on 2023-07-06 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dislikemodel",
            old_name="like",
            new_name="dislike",
        ),
    ]
