# Generated by Django 3.2 on 2023-07-06 13:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0002_rename_like_dislikemodel_dislike"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="likemodel",
            unique_together={("user", "post")},
        ),
    ]
